// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS: return ios;
      case TargetPlatform.macOS: return macos;
      case TargetPlatform.windows: return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for linux');
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPc8g2Yy4OE0ue8pRLHoUt7tV-avF_Jp8',
    appId: '1:584118508324:web:db3aa64376a054a409b1b1',
    messagingSenderId: '584118508324',
    projectId: 'miclan-6dd12',
    authDomain: 'miclan-6dd12.firebaseapp.com',
    storageBucket: 'miclan-6dd12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjg6daP96jsPjQqJa8-hpMFf59Ug13zYA',
    appId: '1:584118508324:android:9412ee86e3ee4f4d09b1b1',
    messagingSenderId: '584118508324',
    projectId: 'miclan-6dd12',
    storageBucket: 'miclan-6dd12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7hbysl9tHZclqnQvUwL1c6h2BXGK8ZFk',
    appId: '1:584118508324:ios:48c85783338e28cb09b1b1',
    messagingSenderId: '584118508324',
    projectId: 'miclan-6dd12',
    storageBucket: 'miclan-6dd12.firebasestorage.app',
    iosBundleId: 'com.agiletask.miclan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7hbysl9tHZclqnQvUwL1c6h2BXGK8ZFk',
    appId: '1:584118508324:ios:48c85783338e28cb09b1b1',
    messagingSenderId: '584118508324',
    projectId: 'miclan-6dd12',
    storageBucket: 'miclan-6dd12.firebasestorage.app',
    iosBundleId: 'com.agiletask.miclan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPc8g2Yy4OE0ue8pRLHoUt7tV-avF_Jp8',
    appId: '1:584118508324:web:17d8978109296e4309b1b1',
    messagingSenderId: '584118508324',
    projectId: 'miclan-6dd12',
    authDomain: 'miclan-6dd12.firebaseapp.com',
    storageBucket: 'miclan-6dd12.firebasestorage.app',
  );
}
